from dash import html, dcc
import dash_bootstrap_components as dbc
from components.alerts import hadeg_alert, toxcsm_alert


def get_features_layout():
    """
    Returns the layout for the BioRemPP Features page.
    """
    return html.Div(
        className="features-page",
        children=[
            # Page Title
            html.H1("BioRemPP Features", className="features-title"),
            html.P(
                "Here, you will find an overview of the platform's functionalities, "
                "tools, and insights into how it can assist in data-driven decision-making for bioremediation studies",
                className="features-intro"
            ),

            # Overview Section
            html.Div(
                children=[
                    html.H2("Platform Overview", className="help-section-title"),
                    html.P(
                        "BioRemPP is a free platform, accessible to all users without requiring a login. Designed to address the global challenge of environmental pollution caused by priority pollutants, BioRemPP leverages advanced data analysis techniques to explore and identify biotechnological potential in bioremediation",
                        className="features-intro"
                    ),
                    html.P(
                        "The platform provides tools for analyzing genomic data to identify microorganisms capable of pollutant degradation, offering a sustainable approach to environmental restoration. By accepting input in .txt format, where each sample is represented by a unique identifier followed by a list of KEGG Orthologs (KOs), BioRemPP delivers comprehensive insights into the bioremediation potential of samples",
                        className="features-intro"
                    ),
                    html.P(
                        "Results generated by BioRemPP are structured into seven key sections, integrating data from BioRemPP, HADEG, and ToxCSM databases. These sections include detailed data tables and visualizations that explore relationships between samples, compounds, genes, and metabolic pathways. The platform offers 20 interactive chart types, enabling users to investigate complex relationships and patterns in their datasets, providing a multi-dimensional characterization of bioremediation potential",
                        className="features-intro"
                    ),
                    html.P(
                        "Powered by Python-based libraries such as Pandas and NumPy for data preprocessing, and scikit-learn for identifying significant patterns, BioRemPP ensures robust data manipulation and analysis. Visualization capabilities are enhanced by Matplotlib and Plotly, delivering interactive and informative charts. The user interface, built with Dash, provides an intuitive and dynamic environment for data exploration",
                        className="features-intro"
                    ),
                    html.P(
                        "This platform is entirely new, representing an innovative approach to genomic data analysis for bioremediation. No comparable tools were identified during its development, and it does not rely on third-party software with restrictive terms",
                        className="features-intro"
                    ),
                ],
                className="features-section"
            ),


            # Expected Results Section
            html.Div(
                id="expected-results-section",
                children=[
                    # Título principal
                    html.H2("Expected Results", className="features-section-title"),
                    html.P(
                        "Explore the insights generated by BioRemPP through its various visualization tools. "
                        "Each result provides detailed information and actionable data to support your research objectives",
                        className="features-text"
                    ),

                    # Seção 1: Main Results Table
                    html.Div([
                        html.H3("1 - Data Tables and Database Integration", className="section-title"),
                        html.P("Provide an overview of the data integrated into the databases", className="section-objective"),
                    ], className="section-header"),
        # Seção 1: Main Results Table
        html.Div(id="main-results-table", className="section"),  # ID para ancoragem no navbar
        html.Div([
            html.H5("BioRemPP Results Table", className="analysis-title"),
            html.P(
                "This table presents the processed data merged with the BioRemPP database, offering a comprehensive overview of the input data and its matched records",
                className="analysis-description"
            ),
            html.P(
                "The merged table reveals how well the input data aligns with the main database, providing insights into the completeness and relevance of the data",
                className="analysis-insights"
            ),
            html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),
        ], className="analysis-header"),

        # Seção 2: HADEG Results Table
        html.Div(id="hadeg-results-table", className="section"),  # ID para ancoragem no navbar
        html.Div([
            html.H5("HADEG Results Table", className="analysis-title"),
            html.P(
                "This table contains data merged with the HADEG database, enabling the exploration of additional annotations and insights",
                className="analysis-description"
            ),
            html.P(
                "The table helps identify significant matches with HADEG, enhancing the understanding of potential functional and structural associations",
                className="analysis-insights"
            ),
            hadeg_alert(),
            html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),
        ], className="analysis-header"),

        # Seção 3: TOXCSM Results Table
        html.Div(id="toxcsm-results-table", className="section"),  # ID para ancoragem no navbar
        html.Div([
            html.H5("ToxCSM Results Table", className="analysis-title"),
            html.P(
                "This table shows data merged with the TOXCSM database, providing toxicity predictions and compound interactions",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this table, you can assess the toxicity potential and prioritize compounds for further investigation",
                className="analysis-insights"
            ),
            toxcsm_alert(),
            html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),
        ], className="analysis-header"),



        # Título e introdução da seção
        html.Div([
            html.H3("2 - Gene and Metabolic Pathway Analysis", className="section-title"),
            html.P(
                "Explore genes and metabolic pathways associated with compounds",
                className="section-objective"
            ),
        ], className="section-header"),

        # Seção 4: Gene Count Chart
        html.Div(id="gene-count-chart", className="section"),
        html.Div([
            html.H5("Gene Count Associated with Priority Compounds", className="analysis-title"),
            html.P(
                "This bar chart displays the count of unique genes associated with priority compounds for each sample",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this chart, you can identify which samples have a higher number of unique gene associations, offering insights into potential hotspots of genetic activity",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 5: Violin Boxplot
        html.Div(id="violin-boxplot", className="section"),
        html.Div([
            html.H5("Gene Distribution", className="analysis-title"),
            html.P(
                "This violin boxplot illustrates the distribution of unique genes associated with priority compounds across samples",
                className="analysis-description"
            ),
            html.P(
                "Identifies trends and outliers in gene distribution, providing a comprehensive view of genetic activity",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 6: Pathway KO Bar Chart
        html.Div(id="pathway-ko-bar-chart", className="section"),
        html.Div([
            html.H5("Distribution of Genes in Xenobiotics Biodegradation Pathways", className="analysis-title"),
            html.P(
                "This bar chart highlights the distribution of KEGG Ortholog (KO) counts across 20 degradation pathways",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this chart, you can gain insights into the functional diversity of pathways and identify dominant or underrepresented pathways in the dataset",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 7: Sample KO Pathway Chart
        html.Div(id="sample-ko-pathway-chart", className="section"),
        html.Div([
            html.H5("Sample-Specific Pathway Activity", className="analysis-title"),
            html.P(
                "This bar chart presents the KEGG Ortholog (KO) distribution across pathways, grouped by sample",
                className="analysis-description"
            ),
            html.P(
                "This visualization allows you to understand how different pathways are represented within each sample, helping to identify pathway-specific trends",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 18: Scatter Plot of KOs by Sample for Pathway
        html.Div(id="sample-ko-scatter", className="section"),
        html.Div([
            html.H5("Sample-Compound Interactions in Xenobiotics Biodegradation Pathways", className="analysis-title"),
            html.P(
                "This scatter plot shows the distribution of genes across different samples for a specific pathway",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this scatter plot, you can identify patterns of genes across samples, helping to pinpoint critical samples for specific pathways",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

            html.Div([
            html.H3("3 - Interactions Between Entities (Samples, Compounds, and Genes)", className="section-title"),
            html.P("Identify interaction patterns between samples, compounds, and genes",
                className="section-objective"
            ),
        ], className="section-header"),

        # Seção 8: Scatter Plot of Samples vs Compounds
        html.Div(id="compound-scatter-chart", className="section"),
        html.Div([
            html.H5("Sample-Compound Interactions", className="analysis-title"),
            html.P(
                "This scatter plot highlights the relationship between samples and compounds, illustrating their interactions and associations",
                className="analysis-description"
            ),
            html.P(
                "Use this visualization to detect key sample-compound interactions and prioritize samples or compounds of interest",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 12: Scatter Plot of Genes vs Compounds
        html.Div(id="gene-compound-scatter-chart", className="section"),
        html.Div([
            html.H5("Gene-Compound Interactions", className="analysis-title"),
            html.P(
                "This scatter plot highlights the relationships between genes and compounds, highlighting associations that may indicate important interactions",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this chart, you can identify gene-compound pairs with potential biological or chemical significance",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 13: Scatter Plot of Samples vs Genes
        html.Div(id="sample-gene-scatter-chart", className="section"),
        html.Div([
            html.H5("Sample-Gene Associations", className="analysis-title"),
            html.P(
                "This scatter plot highlights the relationships between samples and genes, providing insights into genetic patterns across various samples",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this plot, you can identify significant gene associations across different samples, aiding in the discovery of genetic hotspots",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 19: Enzyme Activity Counts per Sample
        html.Div(id="sample-enzyme-activity", className="section"),
        html.Div([
            html.H5("Metabolic Enzyme Activity Counts per Sample", className="analysis-title"),
            html.P(
                "This bar chart shows the distribution of enzyme activity counts across different samples",
                className="analysis-description"
            ),
            html.P(
                "Analyzing enzyme activity counts helps identify variations in enzymatic activity across samples, providing insights into metabolic activity",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 22: Gene-Compound Interaction Network
        html.Div(id="gene-compound-network", className="section"),
        html.Div([
            html.H5("Gene-Compound Interaction Network", className="analysis-title"),
            html.P(
                "This network graph visualizes the interactions between genes and compounds, providing insights into functional relationships",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this graph, you can explore the connectivity and association strength between genes and compounds, uncovering potential targets or key interactions",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),



    html.Div([
        html.H3("4 - Interaction-Based Rankings", className="section-title"),
        html.P(
            "Prioritize samples, genes or compounds based on specific interactions",
            className="section-objective"
        ),
    ], className="section-header"),

    # Seção 9: Ranking of Samples by Compound Interaction
    html.Div(id="sample-rank-compounds-chart", className="section"),
    html.Div([
        html.H5("Sample-Compound Interaction Rankings", className="analysis-title"),
        html.P(
            "This chart ranks samples based on the number and intensity of their interactions with compounds in the dataset",
            className="analysis-description"
        ),
        html.P(
            "By examining this chart, you can identify samples with the most interactions, providing valuable insights into their significance in the analysis",
            className="analysis-insights"
        ),
    ], className="analysis-header"),
    html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

    # Seção 10: Ranking of Compounds by Sample Interaction
    html.Div(id="compound-rank-chart", className="section"),
    html.Div([
        html.H5("Compound-Sample Interaction Rankings", className="analysis-title"),
        html.P(
            "This chart ranks compounds based on their interactions with samples, showcasing which compounds are most significant",
            className="analysis-description"
        ),
        html.P(
            "Use this chart to focus on compounds with the most interactions, which can help prioritize targets for further investigation",
            className="analysis-insights"
        ),
    ], className="analysis-header"),
    html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

    # Seção 11: Ranking of Compounds by Gene Interaction
    html.Div(id="compound-rank-gene-chart", className="section"),
    html.Div([
        html.H5("Compound-Gene Interaction Rankings", className="analysis-title"),
        html.P(
            "This ranking chart identifies compounds with associations with genes, revealing key genetic activity",
            className="analysis-description"
        ),
        html.P(
            "This visualization is useful to prioritize compounds with significant genetic interactions, aiding in targeted research and analysis",
            className="analysis-insights"
        ),
    ], className="analysis-header"),
    html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        html.Div([
            html.H3("5 - Patterns and Interactions with Heatmaps", className="section-title"),
            html.P(
                "This session highlights associations between biological variables such as samples, genes, and pathways",
                className="section-objective"
            ),
        ], className="section-header"),

        # Seção 14: Heatmap of Samples vs Reference AG
        html.Div(id="sample-reference-heatmap", className="section"),
        html.Div([
            html.H5("Sample-Reference Agency Associations Heatmap", className="analysis-title"),
            html.P(
                "This heatmap displays the association between samples and reference agencies, highlighting compound occurrences and interactions",
                className="analysis-description"
            ),
            html.P(
                "Analyze this heatmap to discover hotspots of compound activity linked to reference agencies",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 16: Heatmap of Genes vs Samples
        html.Div(id="gene-sample-heatmap", className="section"),
        html.Div([
            html.H5("Gene-Sample Association Heatmap", className="analysis-title"),
            html.P(
                "This heatmap illustrates the relationship between genes, pathways and samples, providing insights into unique relationships",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this heatmap, you can identify trends and hotspots in the gene-sample-pathways interactions, providing insights into their biological relevance",
                className="analysis-insights"
            ),
            hadeg_alert(),  # Mantém o alerta
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 17: Heatmap of Pathways vs Compound Pathways
        html.Div(id="pathway-heatmap", className="section"),
        html.Div([
            html.H5("Pathway-Compound Heatmap", className="analysis-title"),
            html.P(
                "This heatmap visualizes the interaction between metabolic pathways and compound pathways across samples, highlighting gene activity",
                className="analysis-description"
            ),
            html.P(
                "Use this heatmap to explore how pathways and compound pathways are interconnected for each sample",
                className="analysis-insights"
            ),
            hadeg_alert(),  # Mantém o alerta
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),


                html.Div([
            html.H3("6 - Intersection and Group Exploration", className="section-title"),
            html.P(
                "Investigate overlap and grouping patterns among samples",
                className="section-objective"
            ),
        ], className="section-header"),

        # Seção 15: Sample Groups by Compound Class
        html.Div(id="sample-groups-chart", className="section"),  # ID para link no navbar
        html.Div([
            html.H5("Compound-Based Sample Grouping", className="analysis-title"),
            html.P(
                "Displays how samples are grouped and classified according to their compound content, emphasizing patterns in their composition",
                className="analysis-description"
            ),
            html.P(
                "Use this visualization to detect clusters of samples with similar compound profiles, supporting targeted compound or sample research",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 21: Sample UpSet Plot
        html.Div(id="sample-upset-plot", className="section"),  # ID para link no navbar
        html.Div([
            html.H5("Intersection of Genes Across Samples", className="analysis-title"),
            html.P(
                "This UpSet plot visualizes intersections of orthologous genes (KOs) across multiple samples, highlighting overlaps and unique associations",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this plot, you can identify shared and unique orthologs between samples, highlighting potential relationships and prioritize samples with shared or unique genes for further exploration",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

        # Seção 20: Sample Clustering Dendrogram
        html.Div(id="sample-clustering-dendrogram", className="section"),  # ID para link no navbar
        html.Div([
            html.H5("Hierarchical Clustering of Samples", className="analysis-title"),
            html.P(
                "Hierarchically clusters samples based on genes associated with priority compounds, providing a detailed view of their relationships",
                className="analysis-description"
            ),
            html.P(
                "By analyzing this clustering, you can identify patterns of similarity or divergence between samples",
                className="analysis-insights"
            ),
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),

                html.Div([
            html.H3("7 - Toxicity Predictions", className="section-title"),
            html.P(
                "Visualize and understand toxicity predictions",
                className="section-objective"
            ),
        ], className="section-header"),

        # Seção 23: Heatmap of Toxicity Predictions
        html.Div(id="toxicity-heatmap-faceted", className="section"),  # ID for navbar linking
        html.Div([
            html.H5("Comprehensive Toxicity Heatmap", className="analysis-title"),
            html.P(
                "This heatmap provides a visual representation of toxicity predictions across the five main categories of analysis",
                className="analysis-description"
            ),
            html.P(
                "Explore toxicity predictions to identify high-risk compounds or category, supporting risk assessment and decision-making",
                className="analysis-insights"
            ),
            toxcsm_alert(),  # Alerta preservado conforme solicitado
        ], className="analysis-header"),
        html.Div([dbc.Placeholder(color="success", className="me-1 mt-1 w-100", size="xs")]),
                            ],
                            className="features-section"
                        ),

        # Advanced Tools Section
        html.Div(
            id="additional-tools-section",
            children=[
                html.H2("Advanced Tools and Features", className="features-section-title"),
                
                # General Overview of Advanced Tools
                html.P(
                    "BioRemPP is a comprehensive toolkit designed to unlock deeper insights into complex genomic data for bioremediation pourposes. "
                    "It provides users with a range of analytical tools tailored for bioremediation research, empowering scientists to explore data from multiple dimensions and identify key trends and patterns",
                    className="features-text"
                ),
                
                # Advanced Data Processing Capabilities
                html.P(
                    "These tools are specifically designed to handle high-dimensional data, allowing users to explore the relationships between biological entities and prioritize samples with the greatest bioremediation potential",
                    className="features-text"
                ),
                
                # Interactive Visualizations
                html.P(
                    "The platform offers over 20 types of interactive visualizations, enabling users to dive deeper into the relationships between samples, compounds, genes, and metabolic pathways. "
                    "These visualizations are designed to make complex data more accessible, providing actionable insights through dynamic charts, heatmaps, scatter plots, and network graphs. "
                    "Each visualization is interactive, allowing users to filter, zoom, and explore data points in real-time",
                    className="features-text"
                ),
                                
                # Customizable and Intuitive Interface
                html.P(
                    "The user interface, built with the Dash framework, is highly intuitive and customizable. Users can easily upload datasets, configure analysis parameters, and view results within a streamlined, web-based environment",
                    className="features-text"
                ),
                
            ],
            className="features-section"
        ),


            # Support Section
            html.Div(
                id="support-section",
                children=[
                    html.H2("Need Help?", className="features-section-title"),
                    html.P(
                        "If you have questions about using BioRemPP or interpreting its results, "
                        "visit the Help page or contact our support team. We are here to ensure you make the most of the platform",
                        className="features-text"
                    ),
                    html.A(
                        "Visit the Help Page",
                        href="/help",
                        className="features-link"
                    ),
                ],
                className="features-section"
            ),
        ]
    )
